# Generated by Django 5.1.7 on 2025-04-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_card_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
