# Generated by Django 5.1.7 on 2025-04-01 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
