# Generated by Django 5.1.7 on 2025-04-01 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='board',
            name='likes',
        ),
        migrations.AddField(
            model_name='card',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
